---
- hosts: master
  sudo: True
  vars_files:
    - vars/defaults.yml
  roles:
    - mysql_dump

- hosts: slave
  sudo: True
  vars_files:
    - vars/defaults.yml
  roles:
    - install_mysql
    - import_dump
    - mysql_slave
    - check_slave_status
