---
- name: Update apt cache
  apt: update_cache=yes

- name: Upgrade all safe packages
  apt: upgrade=safe

- name: Install necessities and nice-to-haves
  apt: pkg={{ item }} state=installed
  with_items:
    - mysql-client
    - mysql-common
    - mysql-server

- name: copy dump script
  copy: src=dump-master.sh dest=~/
